apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c0dwu33c3-python-gitops
  description: This is GitOps manifest for c0dwu33c3-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: c0dwu33c3-python
    backstage.io/kubernetes-id: c0dwu33c3-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: c0dwu33c3-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c0dwu33c3-python
