apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c0dwu33c3-python
  janus-idp.io/tekton: c0dwu33c3-python
  backstage.io/kubernetes-id: c0dwu33c3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c0dwu33c3-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
